project:
  type: website  
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "AboutMe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV_updated.qmd
        text: CV
      - href: projects.qmd
        text: Projects
      - href: Make_a_Site.qmd
        text: How to make your own site!

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



