project:
  type: website  
  output-dir: docs

website:
  title: "AboutMe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.pdf
        text: CV
      - href: Make_a_Site.qmd
        text: Make your own site!

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



