project:
  type: website  
  output-dir: docs

website:
  title: "AboutMe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV_Skeeter.qmd
        text: Curriculum Vitae
      - href: projects.qmd
        text: Projects
      - href: Make_a_Site.qmd
        text: How to make your own site!

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true



