---
title: "Curriculum Vitae"
author:
  - name: Dr. June Skeeter
    email: june.skeeter@ubc.ca
    url: https://github.com/June-Skeeter
    pronouns: "they/them/theirs"
    phone: "604 440 1697"
    affiliation:
      name: University of British Columbia
      department: Department of Geography
      city: Vancouver, BC

format: 
  pdf:
    keep-tex: true
    template-partials: 
    #   - before-body.tex
      - title.tex
	    
    include-in-header:
      text: |
        \usepackage[blocks]{authblk}
        \usepackage[a4paper,total={170mm,257mm}, top=20mm, left=20mm]{geometry}
---



<body>
	<div class="head"> <h1>Curriculum Vitae</h1>
		<b>Dr. June Skeeter</b> | <i>they/them</i><br>june.skeeter@ubc.ca | 604.440.1697 | Vancouver, BC
		</div>
		
		<div class="hangingindent">
			
		<h2>Education</h2>
		
		<p>PhD Geography, University of British Columbia, 2022<br>
		<b>Thesis</b>: "Using Machine Learning to Identify and Map Controls of Growing-Season Carbon Dioxide and Methane Fluxes in the Mackenzie Delta Region"</p>
		
		<p>MSc. Geography University of South Carolina, 2015<br>
			<b>Thesis</b>: "Ammonium Concentrations Above a Louisiana Sugarcane Field"</p>
		
		<p>B.S. Geography, B.S Earth Science, and Minor in Statistics, Salisbury University 2013 <br>Graduated Cum Laude</p>
		
		</div>
		
		<div class="block">
		<h2>Current Appointments</h2>
		<table class="col3-right">
			<colgroup>
				<col span="1" width="30%"><col span="1" width="55%"><col span="1" width="15%">
			</colgroup>
			<tr>
				<td>Postdoctoral Researcher</td><td>UBC Geography Department Micrometeorolgy</td>
				<td>2023</td>
			</tr>
			<tr>
				<td>Sessional Instructor</td>
				<td>Geographic Information Systems (GEOS 270), UBC Geography Department</td>
				<td>2020-Present</td>
			</tr>
		
		</table>
		</div>
		
		<div class="block">
		
		<h2>Technical Skills</h2>
		
		<table>
			<colgroup>
				<col span="1" width="33.3%">
				<col span="1" width="33.3%">
				<col span="1" width="33.3%">
			</colgroup>
				<tr>
				<td><h4><u>Field & Research Methods</u></h4></td>
				<td><h4><u>Software & Application</u></h4></td>
				<td><h4><u>Programming/Markup Languages</u></h4></td>
			</tr>
			<tr>
				<td>
					<ul>
						<li>Eddy Covariance Installation & Maintenance</li>
						<li>Flux Data Processing & Footprint Modelling</li>
						<li>Machine Learning</li>
						<li>Spatial Analysis</li>
						<li>Drone Surveying</li>
						<li>Image Classification</li>
					</ul>
				</td>
				<td>
					<ul>
						<li>Git, GitHub, & GitHub Pages</li>
						<li>ArcGIS Pro</li>
						<li>QGIS</li>
						<li>Google Earth Engine</li>
						<li>MapBox & GLJS</li>
						<li>Open Drone Map</li>
						<li>Reveal JS</li>
						<li>Eddy Pro & Smart Flux</li>
					</ul>
				</td>
				<td>
					<ul>
						<li>Python</li>
						<li>JavaScript</li>
						<li>R</li>
						<li>Matlab</li>
						<li>Bash</li>
						<li>Markdown / R Markdown</li>
						<li>HTML</li>
						<li>CSS</li>
					</ul>
				</td>	
			</tr>
		
		</table>
		
		</div>
		
		
		<div class="hangingindent">
		
		<h2>Publications</h2>
		
		<p>Skeeter, J., Christen, A., & Henry, G. H. R. (2022). Controls on Carbon Dioxide and Methane fluxes from a Low-Center Polygonal Peatland in the Mackenzie River Delta. Arctic Science. DOI: <a href = "https://doi.org/10.1139/AS-2021-0034">https://doi.org/10.1139/AS-2021-0034</a></p>
		
		<p>Skeeter, J., Christen, A., Laforce, A.-A., Humphreys, E. and Henry, G. (2020): Vegetation influence and environmental controls on greenhouse gas fluxes from a drained thermokarst lake in the western Canadian Arctic, Biogeosciences, 17(17), 4421-4441, DOI: 
		<a href = "https://doi.org/10.5194/bg-17-4421-2020">https://doi.org/10.5194/bg-17-4421-2020</a></p>
		
		<p>Skeeter, W. R., Parnell, D. B., & Skeeter, B. R. (2016). A Fog Climatology of the Delmarva Peninsula. The Geographical Bulletin, 57(2), 65-75.</p>
		
		<p>Skeeter, W. R.  (2013).  Using radar composites to detect variances in precipitation from cold fronts across the Chesapeake Bay: April through October from 1997 to 2011.  The Pennsylvania Geographer 51(1): 73-86.</p>
		
		<p>Skeeter, J., Christen, A., & Henry, G. H. R. (2022). Modeling Interannual Variability of Carbon Fluxes at a Low-Center Polygon Ecosystem in the Mackenzie River Delta. <i>(Under Review: Arctic Science)</i></p>
		
		<p>Skeeter, J. and Pickell, P. (2022). Data Types and Spatial Data Models. In P.D. Pickell (Ed.), Geomatics for Environmental Management: An Open Textbook for Students and Practitioners (Chapter 3). (n.p). <a href="https://www.opengeomatics.ca/types-of-data">https://www.opengeomatics.ca/types-of-data</a> <i>(In Prep)</i></p>
		
		</div>
		
		<div class="hangingindent">
		
		<h2>Presentations & Lectures</h2>
		
		<p>"Remote Sensing in Atmospheric Sciences", Guest Lecturer, University of British Columbia Department of Geography, GEOB 373 Remote Sensing, March 2022</p>
		
		<p>“Compiling and Mapping Police Involved Deaths: Systemic Racism in Canadian Policing”, Presented at the Western Association of Map Librarians annual meeting, October 29, 2021</p>
		
		<p>“Police Killings and Systemic Racism in Canadian Policing”, Presented at the annual meeting of the Association of American Geographers, April 7th, 2021</p>
		
		<p>"Data Normalization & Classification: Police Violence in North America", Guest Lecturer, University of British Columbia Department of Geography, GEOB 270 Geographic Information Science, November 2020</p>
		
		<p>"Remote Sensing in Atmospheric Sciences", Guest Lecturer, University of British Columbia Department of Geography, GEOB 373 Remote Sensing, November 2020</p>
		
		<p>“EcoMeet Platform Funding Pitch”, presented by Munifa Ahmed & June Skeeter at the David Suzuki Foundation, November 27th, 2019, Vancouver, BC</p>
		
		<p>"How Can I Reduce My Carbon Footprint?”, presented by Munifa Ahmed & June Skeeter for the Ecomeet App at the EcoCity World Summit, October 10th, 2019, Vancouver, BC</p>
		
		<p>“Changes in Summer-to-Winter Precipitation Ratios in the United States Before and After the Onset of Global Warming” Poster, presented by Walker Skeeter at the annual meeting of the Association of American Geographers, April 4th 2019, Washington DC</p>
		
		<p>“Growing Season Carbon Balance of a Permafrost Peatland in the Mackenzie River Delta” Poster presented at European Geophysical Union annual meeting, April 8-13, 2018, Vienna, AT</p>
		
		<p>“Growing Season Carbon Balance of a Mackenzie River Delta Peatland”, Presented at the ArcticNet Conference, December 13th 2017, Quebec City, QC</p>
		
		<p>“Greenhouse Gas Exchange in the Outer Mackenzie Delta” Presented at the Aurora Research Institute Summer Speakers Series, July 8th 2017, Inuvik, NT</p>
		
		<p>“Vegetation Influence and Environmental Controls on Greenhouse Gas Fluxes from a Drained Thermokarst Lake in the Mackenzie River Delta, NWT” Presented the annual meeting of the Canadian Geophysical Union, May 30th, 2017, Vancouver, BC</p>
		
		<p>“Carbon Dioxide and Methane fluxes at Illisarvik 2016”. Poster Presentation at ArcticNet Conference, December 5-9, 2016, Winnipeg, MB</p>
		
		<p>“Intense Precipitation Climatology of South Carolina”. Poster, by Jennifer Simmons at the annual meeting of the Association of American Geographers, April 21-25, 2015, Chicago, IL</p>
		
		<p>“Source Areas of Ammonium Sampled Above a Louisiana Sugarcane Field”. Poster Presentation at the annual meeting of the South Eastern Division of the Association of American Geographers, November 23-25, 2014, Athens, GA</p>
		
		<p>“Identifying Source Areas of Ammonium Concentrations Sampled Above a Louisiana Sugarcane Field”. Presented at the 31st Conference on Agricultural and Forest Meteorology, May 12, 2014, Portland, OR</p>
		
		<p>“Identifying Source Areas of Ammonium Concentrations Sampled Above a Louisiana Sugarcane Field”. Presented at the annual meeting of the Association of American Geographers, April 8, 2014, Tampa, FL</p>
		
		<p>“A Fog Climatology of the Delmarva Peninsula”. Presented by Darren Parnell at the annual meeting of the Middle Atlantic Division of the Association of American Geographers, October 30-November 1, 2013. Annapolis, MD.</p>
		
		<p>“Fog Climatology of Salisbury, MD”. Presented at the Salisbury University Student Research Conference, April 26, 2013-Salisbury, MD</p>
		 
		<p>“Using Radar Composites to Detect Variances in Precipitation from Cold Fronts Across the Chesapeake Bay: April through October from 1997 to 2012”. Presented at the annual meeting of the Association of American Geographers, April 9-12, 2013, Los Angeles, CA</p>
		
		<p>“Using Radar Composites Created in Model Builder to Perform Statistical Analyses of Cold Frontal Precipitation Events in the Chesapeake Bay Region: April through October 1997-2011”. Poster presentation at the annual meeting of the South Eastern Division of the Association of American Geographers, November 18-20, 2012, Asheville, NC</p>
		
		<p>“Using Radar Composites Created in Model Builder to Perform Statistical Analyses of Cold Frontal Precipitation Events in the Chesapeake Bay Region: April through October 1997-2011”. Presented at the joint annual meeting of the Pennsylvania Geographical Society and the Middle Atlantic Division of the Association of American Geographers, November 2-3, 2012, Salisbury, MD</p>
		
		<p>“Using Model Builder to Create Radar Composites for Statistical Sampling and Analysis”. Poster presentation at the Guerrieri Summer Research Program, August 8, 2012, Salisbury, MD</p>
		
		<p>“The Influence of the Chesapeake Bay on April through October Frontal and Squall Line Precipitation Events A Case Study 1980-2010”. Presented at the Salisbury University Student Research Conference, April 27, 2012, Salisbury, MD</p>
		
		<p>“The Possible Differing Influence of the Chesapeake Bay on Frontal and Squall Line Precipitation Events (April-October)”. Poster presentation at the annual meeting the Middle Atlantic Division of the Association of American Geographers, October 28-29, 2011, College Park, MD</p>
		
		<p>“The Possible Differing Influence of the Chesapeake Bay on Frontal and Squall Line Precipitation Events (April-October)”. Poster presentation at the National Science Foundation Bridges Summer Research Program, August 8, 2011, Salisbury, MD</p>
		
		</div>
		
		
		<div class="block">
			
		<h2>Employment History</h2>
		<table class="col3-right">
			<colgroup>
				<col span="1" width="30%"><col span="1" width="55%"><col span="1" width="15%">
			</colgroup>
			<tr>
				<td>Graduate Academic Assistant</td>
				<td>Workshop Creator and GIS Consultant, UBC Library Research Commons</td>
				<td>2020 – 2022</td>
			</tr>
			<tr>
				<td>Graduate Academic Assistant</td>
				<td>Chapter Author, Open Source Geomatics Textbook, University of British Columbia Forestry Department</td>
				<td>2021</td>
			</tr>
			<tr>
				<td>Teaching Assistant</td>
				<td>Introduction to GIS; Remote Sensing; Air Pollution Meteorology; Atmospheric Environments; State of the Earth; Our Changing Climate and Environment, University of British Columbia Geography Department</td>
				<td>2015-2020</td>
			</tr>
			<tr>
				<td>Field Assistant</td>
				<td>Data Collection and Site Maintenance at Burns Bog, University of British Columbia Geography Department</td>
				<td>2020</td>
			</tr>
			<tr>
				<td>Graduate Academic Assistant</td>
				<td>GIS Instructor, Vancouver Summer Program University of British Columbia</td>
				<td>2019</td>
			</tr>
			<tr>
				<td>Research Assistant</td>
				<td>LIDAR Operation and Dispersion Modelling, University of South Carolina</td>
				<td>2013-2015</td>
			</tr>
			<tr>
				<td>Lab Assistant & Tutor</td>
				<td>Undergraduate Lab Supervising; Tutoring in Earth Science and Weather and Climate courses, Salisbury University Department of Geography and Geosciences</td>
				<td>2012-2013</td>
			</tr>
		</table>
		
		</div>
		
		<div class="block">
		
		<h2>Volunteering, Speaking Events, & Committee Positions</h2>
		
		<table class="col3-right">
			<colgroup>
				<col span="1" width="30%"><col span="1" width="55%"><col span="1" width="15%">
			</colgroup>

			<tr>
				<td>Primary Researcher</td>
				<td><a href="https://police-involved-deaths-ca.github.io/Data/">Police Involved Deaths in Canada</a>, Tracking and Mapping Police Violence in Canada</td>
				<td>2020-2022</td>
			</tr>
			<tr>
				<td>Stack Overflow Contributor</td>
				<td>Python and GIS Help, <a href="https://stackoverflow.com/users/5683778/june-skeeter">My Profile</a></td>
				<td>2016-Present</td>
			</tr>
			<tr>
				<td>Guest Speaker</td>
				<td>University of British Columbia Geography Department Undergraduate Events: GIS Cohort Event, Majors Tea</td>
				<td>2021 & 2022</td>
			</tr>
			<tr>
				<td>Graduate Committee Representative</td>
				<td>University of British Columbia Geography Department</td>
				<td>2019-2020</td>
			</tr>
			<tr>
				<td>Climate Consultant</td>
				<td>EcoMeet App</td>
				<td>2019</td>
			</tr>
			<tr>
				<td>Co-chair, Geography Graduate Association</td>
				<td>University of British Columbia Geography Department</td>
				<td>2018-2019</td>
			</tr>
			<tr>
				<td>Geography Bowl Question Contributor</td>
				<td>Middle Atlantic Division of the Association of American Geographers</td>
				<td>2018, 2016</td>
			</tr>
			<tr>
				<td>Departmental Outreach Committee</td>
				<td>University of South Carolina Geography Department</td>
				<td>2014-2015</td>
			</tr>
		</table>
		</div>
		
		<div class="block">
		<h2>Awards</h2>
		
		<table class="col3-right">
			<colgroup>
				<col span="1" width="30%"><col span="1" width="55%"><col span="1" width="15%">
			</colgroup>
		
			<tr>
				<td>Open Educational Resource Champion</td>
				<td>University of British Columbia</td>
				<td>2022</td>
			</tr>
			<tr>
				<td>Four-year Doctoral Fellowship</td>
				<td>University of British Columbia</td>
				<td>2015-2019</td>
			</tr>
			<tr>
				<td>Graduate Assistanceship Award</td>
				<td>University of South Carolina Geography Department</td>
				<td>2013-2015</td>
			</tr>
			<tr>
				<td>Presidential Scholarship</td>
				<td>Salisbury University</td>
				<td>2009-2013</td>
			</tr>
			<tr>
				<td>Eugene D. and Ethel Farace Outstanding Graduating Senior Award</td>
				<td>Salisbury University Department of Geography and Geosciences</td>
				<td>2013</td>
			</tr>
			<tr>
				<td>Outstanding Academic Achievement Award</td>
				<td>Salisbury University Department of Geography and Geosciences</td>
				<td>2013</td>
			</tr>
			<tr>
				<td>Dean’s List</td>
				<td>Salisbury University, Spring 2013; Fall 2012; Fall 2011; Spring 2010; Fall 2009</td>
				<td>2009-2013</td>
			</tr>
		
		
			<tr>
				<td>Association of American Geographers (AAG) World Geography Bowls</td>
				<td>Four-Time Middle Atlantic Division All Star Team Member, 2nd Place Team: 2013 & 2011; 3rd Place Team: 2012; 7th Place Individual Score: 2012</td>
				<td>2010-2013</td>
			</tr>
		
			<tr>
				<td>Middle Atlantic Division AAG Regional Geography Bowls</td>
				<td>Four-Time Team Captain, 2nd Place Team: 2010-2012; 1st Place Team: 2009; 1st Place Individual Score: 2011 & 2009</td>
				<td>2009-2012</td>
			</tr>
		
			<tr>
				<td>1st Place Student Paper Competition</td>
				<td>Joint Annual Meeting of the Pennsylvania Geographical Society and the Middle Atlantic Division of the AAG</td>
				<td>2012</td>
			</tr>
		
			<tr>
				<td>Guerrieri Summer Research Grant</td>
				<td>Salisbury University</td>
				<td>2012</td>
			</tr>
		
			<tr>
				<td>Gamma Theta Upsilon</td>
				<td>Inducted to the International Geographical Honor Society</td>
				<td>2011</td>
			</tr>
			<tr>
				<td>National Science Foundation Bridges Summer Research Grant</td>
				<td>Salisbury University</td>
				<td>2011</td>
			</tr>
			<tr>
				<td>Donald Lee Schul Jr. Memorial Wrestling Scholarship</td>
				<td>Salisbury University</td>
				<td>2009</td>
			</tr>
		</table>
		
		</div>
		
		<div style="page-break-before:always">&nbsp;</div> 
		<div class="block">
			<h2>References</h2>
			<p>Dr. Greg Henry (PhD Co-Supervisor)-Professor Emeritus in Geography, University of British Columbia</p>
				<ul>
					<li>greg.henry@ubc.ca</li>
				</ul>
			<p>Dr. Sara Knox (Postdoc Supervisor)-Associate Professor in Geography, University of British Columbia</p>
				<ul>
					<li>sknox@mail.ubc.ca</li>
				</ul>
			<p>Evan Thornberry (Research Commons Supervisor)-GIS Librarian, University of British Columbia</p>
				<ul>
					<li>evan.thornberry@ubc.ca</li>
				</ul>
		</div>
		
		
</body>