---
title: "Curriculum Vitae"
author:
  - name: Dr. June Skeeter
    email: june.skeeter@ubc.ca
    url: https://june-skeeter.github.io/
    pronouns: "they/them/theirs"
    phone: "604 440 1697"

format: 
  pdf:
    template-partials: 
      - title.tex
    mainfont: TeX Gyre Bonum
	# see for more font options -> https://www.overleaf.com/learn/latex/Font_typefaces#Reference_guide
    linestretch: 1.25
    include-in-header:
      text: |
        \usepackage[blocks]{authblk}
        \usepackage[a4paper,total={170mm,257mm}, top=20mm, left=20mm]{geometry}

  html: 
    code-fold: true

bibliography: MyPublications.bib
section-bibs-bibliography: MyPublications.bib
filters:
  - section-bibliographies
section-bibs-level: 2 # May require edit to line 78 in _extensions/section-bibliographies.lua - have submitted issue
citeproc: false

csl: american-geophysical-union.csl

---

# Education

+-----------------------------------------------------------:+-------:+
|                                                            |        |
+============================================================+=======:+
|PhD Geography, University of British Columbia (UBC)         | 2023   |
+------------------------------------------------------------+--------+
| - {{< var Dissertation >}}                                 |        |
+------------------------------------------------------------+--------+
|                                                            |        |
+------------------------------------------------------------+--------+
| MsC Geography, University of South Carolina (USC)          | 2015   |
+------------------------------------------------------------+--------+
| - {{< var Thesis >}}	                                     |        |
+------------------------------------------------------------+--------+
|                                                            |        |
+------------------------------------------------------------+--------+
| BS Geography & BS Earth Science, Salisbury University (SU) | 2013   |
+------------------------------------------------------------+--------+
| - Minor in Statistics                                      |        |
| - Graduated Cum Laude                                      |        |
+------------------------------------------------------------+--------+

: {tbl-colwidths="[90,10]"}

# Employment

+----------------------------------------------------------:+---------------:+
|                                                           |                |
+===========================================================+===============:+
| Postdoc, UBC Micrometeorolgy                              | 2022 - Present |
+-----------------------------------------------------------+----------------+
| Sessional Instructor, UBC Geography Department            | 2020 - Present |
+-----------------------------------------------------------+----------------+
| Graduate Academic Assistant, UBC Library Research Commons | 2020 - 2022    |
+-----------------------------------------------------------+----------------+
| Graduate Academic Assistant, Vancouver Summer Program UBC | 2019           |
+-----------------------------------------------------------+----------------+
| Teaching Assistant, UBC Geography Department              | 2015 - 2020    |
+-----------------------------------------------------------+----------------+
| Research Assistant, USC Geography Department              | 2013 - 2015    |
+-----------------------------------------------------------+----------------+
| Lab Assistant & Tutor, SU Geography Department            | 2013 - 2015    |
+-----------------------------------------------------------+----------------+

: {tbl-colwidths="[80,20]"}

# Publications

## Peer Reviewed

::: {.content-visible when-format="html"}
::: {.hidden}

@skeeter_controls_2022
@skeeter_vegetation_2020
@skeeter_fog_2016
@skeeter_using_2013

:::
:::



## Book chapter

::: {.content-visible when-format="html"}
::: {.hidden}

@skeeter_chapter_2022

:::
:::



# Presentations

## Research Talks

::: {.content-visible when-format="html"}
::: {.hidden}

@skeeter_compiling_2021
@skeeter_police_2021
@ahmed_how_2019
@skeeter_growing_2017
@skeeter_greenhouse_2017
@skeeter_vegetation_2017
@skeeter_carbon_2016
@skeeter_identifying_2014-1
@skeeter_identifying_2014-2
@skeeter_fog_2013
@skeeter_using_2013
@skeeter_using_2012-2

:::
:::

## Guest Lectures

::: {.content-visible when-format="html"}
::: {.hidden}

@skeeter_remote_2022
@skeeter_data_2020
@skeeter_remote_2020

:::
:::


## Poster Presentations

::: {.content-visible when-format="html"}
::: {.hidden}

@skeeter_growing_2018
@skeeter_carbon_2016
@skeeter_source_2014
@skeeter_using_2012-1
@skeeter_possible_2011

:::
:::



# Technical Skills 


+:-------------------------------+:-------------------------------+:------------------------+
| Field & Research Methods       | Programming & Markup Languages | Software & Applications |
+:===============================+:===============================+:========================+
| - Eddy Covariance              | - Python                       | - Git & GitHub          |
| - Footprint Modelling          | - Javascript                   | - ArcGIS Pro & QGIS     |
| - Flux Chamber Sampling        | - Matlab                       | - Google Earth Engine   |
| - Drone Surveying              | - R                            | - Mapbox API            |
| - Machine Learning             | - HTML                         | - Loggernet             |
| - Image Classification         | - Markdown                     | - Eddy Pro              |
|                                |                                | - Quarto                |
+--------------------------------+--------------------------------+-------------------------+

: {tbl-colwidths="[33,33,33]"}

# Volunteer Work and Committee Positions

+-----------------------------------------------------------:+---------------:+
| 											                 |                |
+============================================================+===============:+
| Western Director, {{< var CSFAM >}}                        | 2023 - Present |
+------------------------------------------------------------+----------------+
| {{< var PID >}}                                            | 2020 - Present |
+------------------------------------------------------------+----------------+
| Graduate Committee Representative, UBC Geography           | 2019 - 2020    |
+------------------------------------------------------------+----------------+
| Climate Consultant, EcoMeet App                            | 2019           |
+------------------------------------------------------------+----------------+
| Co-chair, UBC Geography Graduate Student Association       | 2018 - 2018    |
+------------------------------------------------------------+----------------+
| USC Geography Departmental Outreach Committee              | 2018 - 2018    |
+------------------------------------------------------------+----------------+

: {tbl-colwidths="[80,20]"}

# Awards

+-----------------------------------------------------------:+------------:+
| 											                 |             |
+============================================================+============:+
| Open Educational Resource Champion, UBC Alma Mater Society | 2022        |
+------------------------------------------------------------+-------------+
| Four-year Doctoral Fellowship, UBC                         | 2015 - 2019 |
+------------------------------------------------------------+-------------+
| Graduate Assistanceship Award, UBC                         | 2013 - 2015 |
+------------------------------------------------------------+-------------+
| Presidential Scholarship, SU                               | 2009 - 2013 |
+------------------------------------------------------------+-------------+
| {{< var AAG >}} World Geography Bowls                      | 2009 - 2013 |
+------------------------------------------------------------+-------------+
| - Four-time All Star Team Member, Middle Atlantic Division |             |
+------------------------------------------------------------+-------------+
| Outstanding Graduating Senior Award, SU Geography          | 2013        |
+------------------------------------------------------------+-------------+
| Outstanding Academic Achievement Award, SU Geography       | 2013        |
+------------------------------------------------------------+-------------+
| 1st Place Student Paper {{< var MADAAG >}} Annual Meeting  | 2012        |
+------------------------------------------------------------+-------------+
| Donald Lee Schul Jr. Memorial Wrestling Scholarship, SU    | 2009        |
+------------------------------------------------------------+-------------+

: {tbl-colwidths="[80,20]"}
