---
title: "Make your own website!"
---

This webpage was created using [Quarto](https://quarto.org/) and is hosted using Github Pages.  Quarto is an open source scientific writing package that allows you write articles, create presentations, and publish websites using Markdown.  It supports integration with Python and R, and can render to multiple different formats, including: .pdf, .docx, .html, .pptx.

If you want to make your own, the first step is to [download and install Quarto](https://quarto.org/docs/get-started/).  It can be run in RStudio, VSCode, or from command line.  To learn more about Quarto visit: <https://quarto.org/docs/websites>.

To host a personal website you need to create a Github repository using this format: User-Name.github.io

* This isn't necessary to host a regular webpage with Github, only if you want to make a "homepage" for yourself. i.e., the repo for this site is: [https://github.com/June-Skeeter/june-skeeter.github.io](https://github.com/June-Skeeter/june-skeeter.github.io), so when the page is rendered it shows up as [https://june-skeeter.github.io/](https://june-skeeter.github.io/)

* You can use other naming conventions if you don't need this.  i.e., the here is a repo hosted on the micromet github: [https://github.com/ubc-micromet/FieldSiteMaps](https://github.com/ubc-micromet/FieldSiteMaps), and the corresponding github page address is [https://ubc-micromet.github.io/FieldSiteMaps/](https://ubc-micromet.github.io/FieldSiteMaps/)
